import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'FA-3: Basic Layout & Global Styling',
  description: 'Generated by create next app for FA-3 ticket',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ backgroundColor: '#333', color: '#fff', padding: '1rem', textAlign: 'center' }}>
          <h1>My Application</h1>
        </header>
        <main style={{ minHeight: '80vh', padding: '2rem' }}>
          {children}
        </main>
        <footer style={{ backgroundColor: '#333', color: '#fff', padding: '1rem', textAlign: 'center', marginTop: '2rem' }}>
          <p>&copy; 2023 My Application</p>
        </footer>
      </body>
    </html>
  );
}
